### ISSUE TITLE
Errors using const and let keywords

### ISSUE THREAD

**Issue by rabbitwerks** [TonyCletus/Gulpjs-Boilerplate#1]
Error using const and let keywords in js files being minified by uglify.

Consider using gulp-babel in addition to these plugins to support es6 javascript syntax. Might want to include that as part of the boilerplate structure.

**Comment by tonycletus** [comment]
Yeah!!! Nice Observation Sharpie

Implementation done 100%:  check line 9 and 41 on **gulpfile.js file**

Once again Thanks a million
